trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
   - job: FirstJob
     steps:
     - bash: echo FirstJob, First Step!
     - bash: echo $(PipelineLevelVariable)
     - bash: echo python --version
     - bash: echo java -version
     - bash: echo node --version
     - bash: echo mvn -version

     - bash: echo $(System.DefaultWorkingDirectory)
     - bash: ls -R $(System.DefaultWorkingDirectory)
     - bash: echo $(Build.ArtifactStagingDirectory)
     - bash: ls -R $(Build.ArtifactStagingDirectory)
     
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: |
           **/*.yaml
           **/*.tf
         TargetFolder: '$(Build.ArtifactStagingDirectory)'
     - bash: ls -R $(Build.ArtifactStagingDirectory)   
     
     - task: PublishPipelineArtifact@1
       inputs:
         targetPath: '$(Build.ArtifactStagingDirectory)'
         artifact: 'buildarti_demo'
         publishLocation: 'pipeline'
         
#    - job: SecondJob
#      steps:
#      - bash: echo SecondJob, First Step!
#  - stage: DevDeploy
#    variables:
#     environment: Dev 
#    dependsOn: Build
#    jobs:
#    - job: DevDeploy
#      steps:
#      - bash: echo $(environment)Deploy, First Step!
#  - stage: QADeploy
#    variables:
#     environment: QA
#    dependsOn: DevDeploy
#    jobs:
#    - job: QADeploy
#      steps:
#      - bash: echo $(environment)Deploy, First Step!
#  - stage: ProdDeploy
#    variables:
#     environment: Prod
#    dependsOn:
#    - DevDeploy
#    - QADeploy
#    jobs:
#    - job: ProdDeploy
#      steps:
#      - bash: echo $(environment)Deploy, First Step!