trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage: Build
   jobs:
   - job: FirstJob
     steps:
     - script: echo FirstJob, First Step!
   - job: SecondJob
     steps:
     - script: echo SecondJob, First Step!
 - stage: DevDeploy
   dependsOn: Build
   jobs:
   - job: DevDeploy
     steps:
     - script: echo DevDeploy, First Step!
 - stage: QADeploy
   dependsOn: DevDeploy
   jobs:
   - job: QADeploy
     steps:
     - script: echo QADeploy, First Step!
 - stage: ProdDeploy
   dependsOn:
   - DevDeploy
   - QADeploy
   jobs:
   - job: ProdDeploy
     steps:
     - script: echo ProdDeploy, First Step!